## Shared configuration among all services
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
spring:
  kafka:
#    bootstrap-servers: 10.1.66.33:9092
    bootstrap-servers: 10.1.66.33:9092
