## Shared configuration among all services
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
spring:
  kafka:
    bootstrap-servers: http://localhost:29092