management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
server:
  port: 8082

spring:
  application:
    name: second-client
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: development
      label: dev
    bus:
      destination: myTopic
