management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
server:
  port: 8082

spring:
  application:
    name: second-client
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
#      uri: http://localhost:8888
      profile: development
      label: dev
    bus:
      enabled: true
      trace:
        enabled: true
      ack:
        enabled: true
      refresh:
        enabled: true
#      destination: myTopic
