management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
server:
  port: 8888
spring:
  profiles:
    active: jdbc
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/configserver
    username: root
    password: secret
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  application:
    name: config-server
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT CODE, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
        order: 1
#        git:
#          uri: https://github.com/hienpv/spring-cloud-bus-config-server.git
#          search-paths: config-properties
    bus:
      enabled: true
      id: config-server
#      destination: myTopic
      trace:
        enabled: true
#    server:
#      encrypt:
#        enabled: true

#encrypt:
#  key: ${ENCRYPT_KEY}
#  fail-on-error: false