server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hienpv/spring-cloud-bus-config-server.git
          search-paths: config-properties
    bus:
      enabled: true
      id: config-server
      destination: myTopic
    server:
      encrypt:
        enabled: true

encrypt:
  key: ${ENCRYPT_KEY}
  fail-on-error: false